const {chromium}=require('C:/Users/husih/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const page=await b.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));const results=[];fs.mkdirSync('finite-fields-book/_build/standalone-check',{recursive:true});
 for(const path of ['intro',...Array.from({length:19},(_,i)=>`chapters/c${String(i+1).padStart(2,'0')}`),'appendices/source','appendices/algorithms','appendices/references','appendices/experiments']){
  await page.goto(`http://127.0.0.1:8765/${path}.html`);await page.waitForFunction(()=>!!document.querySelector('mjx-container svg'));await page.evaluate(()=>window.MathJax.startup.promise);
  assert.equal(await page.locator('[data-mml-node="merror"]').count(),0,path+' math errors');
  const text=await page.locator('article').innerText();assert.equal(/PPT|新增|原讲义|原页|逐页|转写|第\s*\d+\s*页/.test(text),false,path+' source wording');assert.equal(await page.locator('.reader-original,img[src*="slides/"],a[href*="original/"]').count(),0);
  const broken=await page.evaluate(()=>[...document.querySelectorAll('article a[href^="#"]')].filter(a=>a.hash&&a.hash!=='#'&&!document.getElementById(decodeURIComponent(a.hash.slice(1)))).map(a=>a.hash));assert.deepEqual(broken,[],path+' broken anchors');
  if(path.startsWith('chapters/')){
   assert.equal(await page.locator('.chapter-goals').count(),1);assert.equal(await page.locator('.chapter-note').count(),1);assert.equal(await page.locator('.export-notes').count(),1);
   const headings=await page.locator('h2').allTextContents();assert.ok(headings.some(t=>t.includes('学习检查')));assert.ok(headings.some(t=>t.includes('学习笔记')));
   assert.equal(await page.locator('.lesson-error').count(),0);await page.locator('.quiz [data-correct="yes"]').click();assert.match(await page.locator('.quiz-feedback').innerText(),/回答正确/);
   const numbers=await page.locator('.source-label,.statement-title').allTextContents();assert.equal(new Set(numbers.filter(x=>/^(定义|定理|例|命题|引理|推论|练习) \d+\.\d+$/.test(x))).size,numbers.filter(x=>/^(定义|定理|例|命题|引理|推论|练习) \d+\.\d+$/.test(x)).length,path+' duplicate statement numbers');
   await page.locator('.source-line').nth(1).click();await page.keyboard.press('ArrowDown');assert.match(await page.locator('#reader-position').innerText(),/3 \/ \d+ 段/);assert.match(await page.locator('.source-line').first().getAttribute('data-line'),/^第 1 段$/);
   const note=page.locator('.chapter-note');await note.fill('独立教材笔记验证');await page.reload();assert.equal(await note.inputValue(),'独立教材笔记验证');await note.fill('');
  }
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,path+' mobile overflow');
  results.push({path,mathErrors:0,sourceWordingRemoved:true,mobilePassed:true});console.log(path+' passed.');await page.setViewportSize({width:1280,height:900});
 }
 await page.goto('http://127.0.0.1:8765/chapters/c01.html');await page.evaluate(()=>{localStorage.removeItem('finitefields:/chapters/c01.html:chapter');localStorage.setItem('finitefields:/chapters/c01.html:1','旧笔记甲');localStorage.setItem('finitefields:/chapters/c01.html:3','旧笔记乙');});await page.reload();assert.equal(await page.locator('.chapter-note').inputValue(),'旧笔记甲\n\n---\n\n旧笔记乙');
 const dl=page.waitForEvent('download');await page.locator('.export-notes').click();const download=await dl;await download.saveAs('finite-fields-book/_build/standalone-check/exported-notes.txt');assert.match(fs.readFileSync('finite-fields-book/_build/standalone-check/exported-notes.txt','utf8'),/旧笔记甲[\s\S]*旧笔记乙/);
 await page.goto('http://127.0.0.1:8765/chapters/c09.html');const proof=page.locator('#c09-splitting-field-proof');assert.match(await proof.locator('.admonition-title').innerText(),/高阶选读/);await proof.locator('.admonition-title').click();assert.equal(await proof.locator('p').nth(1).isVisible(),true);
 await page.goto('http://127.0.0.1:8765/intro.html');await page.screenshot({path:'finite-fields-book/_build/standalone-check/home-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForFunction(()=>!!document.querySelector('mjx-container svg'));await page.screenshot({path:'finite-fields-book/_build/standalone-check/home-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);fs.writeFileSync('finite-fields-book/_build/standalone-validation.json',JSON.stringify({pages:results,legacyNotesMigrated:true,notesExportPassed:true,advancedProofPreserved:true,browserErrors:errors},null,2));console.log('Standalone textbook: all pages, formulas, anchors, numbering, notes migration/export and advanced proof passed.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
