const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require('C:/Users/husih/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
global.window={};require('../_static/knowledge-data.js');const D=window.FFKnowledge;
const out='finite-fields-book/_build/knowledge-check';fs.mkdirSync(out,{recursive:true});
assert.equal(new Set(D.nodes.map(n=>n.id)).size,D.nodes.length);
for(const n of D.nodes){const html=fs.readFileSync(`finite-fields-book/_build/html/chapters/${n.chapter}.html`,'utf8');for(const anchor of [n.anchor,...(n.extra?[n.extra.anchor]:[])])assert.ok(html.includes(`id="${anchor}"`),n.id+' anchor '+anchor);for(const k of ['summary','formula','conditions'])assert.ok(n[k],n.id+' '+k);}
for(const e of D.edges){assert.ok(D.byId.has(e.from)&&D.byId.has(e.to));assert.ok(D.relations[e.type]);assert.notEqual(e.from,e.to);}
assert.equal(new Set(D.edges.map(e=>[e.from,e.to,e.type].join(':'))).size,D.edges.length);
for(const c of D.chapters)assert.ok(D.nodes.some(n=>n.chapter===c.id));
for(const r of D.routes)for(const id of r.ids)assert.ok(D.byId.has(id));
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const context=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce',acceptDownloads:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765/knowledge.html');await page.waitForSelector('#kg-map-tab');assert.equal(await page.locator('.kg-part').count(),5);assert.equal(await page.locator('.kg-part button').count(),19);
 await page.screenshot({path:out+'/overview-desktop.png',fullPage:true});
 for(const [index,n] of D.nodes.entries()){
  await page.evaluate(id=>{location.hash='node='+id},n.id);await page.waitForFunction(title=>document.querySelector('#kg-detail h3')?.textContent===title,n.title);
  await page.waitForFunction(()=>!!document.querySelector('#kg-detail mjx-container svg'));
  assert.equal(await page.locator('#kg-detail [data-mml-node="merror"]').count(),0,n.id+' formula');
  assert.equal(await page.locator('#kg-detail a').first().getAttribute('href'),`chapters/${n.chapter}.html#${n.anchor}`);
  if(index%30===0)console.log('Rendered '+(index+1)+'/'+D.nodes.length+' concept formulas.');
 }
 await page.locator('#kg-chapter').selectOption('c13');await page.locator('#kg-search').fill('迹');assert.ok((await page.locator('#kg-catalog button').count())>=4);assert.ok((await page.locator('#kg-catalog').innerText()).includes('相对迹'));
 await page.evaluate(()=>{location.hash='node=trace'});await page.waitForFunction(()=>document.querySelector('#kg-detail h3')?.textContent==='相对迹');await page.locator('#kg-status').selectOption('learning');await page.locator('#kg-difficulty').selectOption('proof');await page.locator('#kg-note').fill('不理解轨道长度与扩张次数。<img src=x onerror=alert(1)>');await page.getByRole('button',{name:'保存学习记录',exact:true}).click();await page.reload();await page.waitForSelector('#kg-note');assert.match(await page.locator('#kg-note').inputValue(),/不理解轨道/);assert.equal(await page.locator('#kg-status').inputValue(),'learning');
 await page.getByRole('button',{name:'记录一次复习',exact:true}).click();await page.locator('#kg-study-tab').click();assert.equal(await page.locator('.kg-hard').count(),1);assert.equal(await page.locator('.kg-hard img').count(),0);assert.match(await page.locator('.kg-metrics').innerText(),/1\/134/);assert.equal(await page.locator('.kg-progress-card').count(),19);assert.match(await page.locator('.kg-hard').innerText(),/可先回顾/);
 const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'导出学习记录',exact:true}).click();await (await downloaded).saveAs(out+'/export.json');const backup=JSON.parse(fs.readFileSync(out+'/export.json','utf8'));assert.equal(backup.records.trace.difficulty,'proof');assert.ok(backup.records.trace.reviewed);
 const imported=structuredClone(backup);imported.records.trace.note='更旧的记录不能覆盖';imported.records.trace.updated='2020-01-01T00:00:00.000Z';imported.records.primitive={status:'mastered',difficulty:'none',note:'可以独立检验本原元。',updated:new Date().toISOString(),reviewed:''};fs.writeFileSync(out+'/import.json',JSON.stringify(imported));await page.locator('#kg-import').setInputFiles(out+'/import.json');await page.waitForFunction(()=>document.querySelector('#kg-storage-message').textContent.includes('已合并 1 条'));const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('finitefields:learning:v1')).records);assert.match(stored.trace.note,/不理解轨道/);assert.equal(stored.primitive.status,'mastered');
 const invalid=structuredClone(imported);invalid.records.trace.status='forged';fs.writeFileSync(out+'/invalid.json',JSON.stringify(invalid));await page.locator('#kg-import').setInputFiles(out+'/invalid.json');await page.waitForFunction(()=>document.querySelector('#kg-storage-message').textContent.includes('导入失败'));assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('finitefields:learning:v1')).records),stored);
 await page.screenshot({path:out+'/study-desktop.png',fullPage:true});
 await page.locator('#kg-map-tab').click();await page.locator('#kg-depth').selectOption('2');await page.locator('#kg-direction').selectOption('before');const before=await page.locator('#kg-canvas g[role=button]').count();assert.ok(before>2);await page.locator('#kg-direction').selectOption('after');assert.ok((await page.locator('#kg-canvas g[role=button]').count())>1);
 await page.locator('#kg-direction').selectOption('both');const all=await page.locator('#kg-canvas path[marker-end]').count();await page.locator('[data-relation=prerequisite]').uncheck();assert.ok((await page.locator('#kg-canvas path[marker-end]').count())<all);await page.locator('[data-relation=prerequisite]').check();
 await page.locator('#kg-depth').selectOption('1');const neighbor=page.locator('#kg-canvas g[role=button]:not(.is-selected)').first(),neighborId=await neighbor.getAttribute('data-node-id');await neighbor.focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#kg-detail h3').innerText(),D.byId.get(neighborId).title);
 await page.evaluate(()=>{location.hash='node=mult-cyclic'});await page.waitForFunction(()=>document.querySelector('#kg-detail h3')?.textContent==='有限域乘法群是循环群');await page.locator('#kg-depth').selectOption('2');await page.screenshot({path:out+'/graph-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForSelector('#kg-detail h3');await page.waitForFunction(()=>!!document.querySelector('#kg-detail mjx-container svg'));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'mobile map overflow');await page.locator('#kg-work').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/graph-mobile.png',fullPage:true});await page.locator('#kg-study-tab').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'mobile study overflow');await page.screenshot({path:out+'/study-mobile.png',fullPage:true});
 await context.setOffline(true);await page.locator('#kg-map-tab').click();await page.locator('#kg-kind').selectOption('定理');assert.ok((await page.locator('#kg-catalog button').count())>0);await page.locator('#kg-depth').selectOption('2');assert.ok((await page.locator('#kg-canvas g[role=button]').count())>1);await context.setOffline(false);
 await page.goto('http://127.0.0.1:8765/chapters/c11.html');await page.waitForSelector('.kg-chapter-panel');assert.match(await page.locator('.kg-chapter-panel').innerText(),/掌握 1\/5/);assert.equal(await page.locator('.kg-chapter-panel a').first().getAttribute('href'),'../knowledge.html#chapter=c11&view=map');
 await page.goto('http://127.0.0.1:8765/knowledge.html#chapter=c11&view=study');await page.waitForSelector('#kg-study:not([hidden])');assert.equal(await page.locator('#kg-chapter').inputValue(),'c11');
 await page.emulateMedia({colorScheme:'dark'});await page.locator('#kg-map-tab').click();await page.screenshot({path:out+'/dark-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);fs.writeFileSync(out+'/validation.json',JSON.stringify({nodes:D.nodes.length,edges:D.edges.length,chapters:19,allAnchors:true,allFormulas:true,learningPersistence:true,exportImportMerge:true,invalidImportUnchanged:true,keyboard:true,mobile:true,offlineInteraction:true,errors},null,2));console.log('Knowledge graph and learning dashboard validation passed.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
